[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18.17.0" }

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 